/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as LivreRouteImport } from './routes/livre'
import { Route as GoodsRouteImport } from './routes/goods'
import { Route as IndexRouteImport } from './routes/index'

const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const LivreRoute = LivreRouteImport.update({
  id: '/livre',
  path: '/livre',
  getParentRoute: () => rootRouteImport,
} as any)
const GoodsRoute = GoodsRouteImport.update({
  id: '/goods',
  path: '/goods',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/goods': typeof GoodsRoute
  '/livre': typeof LivreRoute
  '/vault': typeof VaultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/goods': typeof GoodsRoute
  '/livre': typeof LivreRoute
  '/vault': typeof VaultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/goods': typeof GoodsRoute
  '/livre': typeof LivreRoute
  '/vault': typeof VaultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/goods' | '/livre' | '/vault'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/goods' | '/livre' | '/vault'
  id: '__root__' | '/' | '/goods' | '/livre' | '/vault'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GoodsRoute: typeof GoodsRoute
  LivreRoute: typeof LivreRoute
  VaultRoute: typeof VaultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livre': {
      id: '/livre'
      path: '/livre'
      fullPath: '/livre'
      preLoaderRoute: typeof LivreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goods': {
      id: '/goods'
      path: '/goods'
      fullPath: '/goods'
      preLoaderRoute: typeof GoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GoodsRoute: GoodsRoute,
  LivreRoute: LivreRoute,
  VaultRoute: VaultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
